const SUCCESS = 200;
const NO_CONTENT = 204;
const INVALID_REQUEST = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const IMPROPER_REQUEST = 406;
const ERROR = 500;
const UNDER_DEVELOPMENT = 501;

module.exports = {
  SUCCESS: SUCCESS,
  NO_CONTENT: NO_CONTENT,
  INVALID_REQUEST: INVALID_REQUEST,
  UNAUTHORIZED: UNAUTHORIZED,
  FORBIDDEN: FORBIDDEN,
  IMPROPER_REQUEST: IMPROPER_REQUEST,
  ERROR: ERROR,
  UNDER_DEVELOPMENT: UNDER_DEVELOPMENT,
};
